In [1]:

import types
import pandas as pd
from botocore.client import Config
import ibm_boto3

def __iter__(self): return 0

# @hidden_cell
# The following code accesses a file in your IBM Cloud Object Storage. It includes your credentials.
# You might want to remove those credentials before you share your notebook.
client_5aa2e59a16dd4defa030da7ac7c17757 = ibm_boto3.client(service_name='s3',
    ibm_api_key_id='qFxPNcjka3-QBVoxWdRrsy337qgjzRNCoq_yd5WIawhT',
    ibm_auth_endpoint="https://iam.bluemix.net/oidc/token",
    config=Config(signature_version='oauth'),
    endpoint_url='https://s3.eu-geo.objectstorage.service.networklayer.com')

body = client_5aa2e59a16dd4defa030da7ac7c17757.get_object(Bucket='predictionofdiabetesmellitus-donotdelete-pr-w2ywpgsghceepy',Key='diabetes.csv')['Body']
# add missing __iter__ method, so pandas accepts body as file-like object
if not hasattr(body, "__iter__"): body.__iter__ = types.MethodType( __iter__, body )

dataset= pd.read_csv(body)
dataset.head()

import numpy as np
import pandas as pd

In [2]:
#dataset=pd.read_csv("C:/Users/Suguna Simhadri/Desktop/diabetes.csv")

In [3]:
dataset.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
dataset.isnull().any()

Pregnancies                 False
Glucose                     False
BloodPressure               False
SkinThickness               False
Insulin                     False
BMI                         False
DiabetesPedigreeFunction    False
Age                         False
Outcome                     False
dtype: bool

In [5]:
x=dataset.iloc[:,:8]
y=dataset.iloc[:,8]

In [6]:
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
5              5      116             74              0        0  25.6   
6              3       78             50             32       88  31.0   
7             10      115              0              0        0  35.3   
8              2      197             70             45      543  30.5   
9              8      125             96              0        0   0.0   
10             4      110             92              0        0  37.6   
11            10      168             74              0        0  38.0   
12            10      139             80              0        0  27.1   
13             1      189             60             23      846  30.1   
14             5      166             72             19      175  25.8   
15             7      100              0              0        0  30.0   
16             0      118             84             47      230  45.8   
17             7      107             74              0        0  29.6   
18             1      103             30             38       83  43.3   
19             1      115             70             30       96  34.6   
20             3      126             88             41      235  39.3   
21             8       99             84              0        0  35.4   
22             7      196             90              0        0  39.8   
23             9      119             80             35        0  29.0   
24            11      143             94             33      146  36.6   
25            10      125             70             26      115  31.1   
26             7      147             76              0        0  39.4   
27             1       97             66             15      140  23.2   
28            13      145             82             19      110  22.2   
29             5      117             92              0        0  34.1   
..           ...      ...            ...            ...      ...   ...   
738            2       99             60             17      160  36.6   
739            1      102             74              0        0  39.5   
740           11      120             80             37      150  42.3   
741            3      102             44             20       94  30.8   
742            1      109             58             18      116  28.5   
743            9      140             94              0        0  32.7   
744           13      153             88             37      140  40.6   
745           12      100             84             33      105  30.0   
746            1      147             94             41        0  49.3   
747            1       81             74             41       57  46.3   
748            3      187             70             22      200  36.4   
749            6      162             62              0        0  24.3   
750            4      136             70              0        0  31.2   
751            1      121             78             39       74  39.0   
752            3      108             62             24        0  26.0   
753            0      181             88             44      510  43.3   
754            8      154             78             32        0  32.4   
755            1      128             88             39      110  36.5   
756            7      137             90             41        0  32.0   
757            0      123             72              0        0  36.3   
758            1      106             76              0        0  37.5   
759            6      190             92              0        0  35.5   
760      

In [7]:
type(x)

pandas.core.frame.DataFrame

In [8]:
y

0      1
1      0
2      1
3      0
4      1
5      0
6      1
7      0
8      1
9      1
10     0
11     1
12     0
13     1
14     1
15     1
16     1
17     1
18     0
19     1
20     0
21     0
22     1
23     1
24     1
25     1
26     1
27     0
28     0
29     0
      ..
738    0
739    1
740    1
741    0
742    0
743    1
744    0
745    0
746    1
747    0
748    1
749    1
750    1
751    0
752    0
753    1
754    1
755    1
756    0
757    1
758    0
759    1
760    0
761    1
762    0
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [9]:
type(y)

pandas.core.series.Series

In [10]:
x=dataset.iloc[:,:8].values
y=dataset.iloc[:,8].values

In [11]:
x

array([[   6.   ,  148.   ,   72.   , ...,   33.6  ,    0.627,   50.   ],
       [   1.   ,   85.   ,   66.   , ...,   26.6  ,    0.351,   31.   ],
       [   8.   ,  183.   ,   64.   , ...,   23.3  ,    0.672,   32.   ],
       ..., 
       [   5.   ,  121.   ,   72.   , ...,   26.2  ,    0.245,   30.   ],
       [   1.   ,  126.   ,   60.   , ...,   30.1  ,    0.349,   47.   ],
       [   1.   ,   93.   ,   70.   , ...,   30.4  ,    0.315,   23.   ]])

In [12]:
y

array([1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 1,

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=0)

In [14]:
x_train

array([[  0.00000000e+00,   1.51000000e+02,   9.00000000e+01, ...,
          4.21000000e+01,   3.71000000e-01,   2.10000000e+01],
       [  1.00000000e+00,   8.30000000e+01,   6.80000000e+01, ...,
          1.82000000e+01,   6.24000000e-01,   2.70000000e+01],
       [  2.00000000e+00,   1.22000000e+02,   7.00000000e+01, ...,
          3.68000000e+01,   3.40000000e-01,   2.70000000e+01],
       ..., 
       [  4.00000000e+00,   9.40000000e+01,   6.50000000e+01, ...,
          2.47000000e+01,   1.48000000e-01,   2.10000000e+01],
       [  1.10000000e+01,   8.50000000e+01,   7.40000000e+01, ...,
          3.01000000e+01,   3.00000000e-01,   3.50000000e+01],
       [  5.00000000e+00,   1.36000000e+02,   8.20000000e+01, ...,
          0.00000000e+00,   6.40000000e-01,   6.90000000e+01]])

In [15]:
x_train.shape

(537, 8)

In [16]:
x_test

array([[  1.00000000e+00,   1.99000000e+02,   7.60000000e+01, ...,
          4.29000000e+01,   1.39400000e+00,   2.20000000e+01],
       [  2.00000000e+00,   1.07000000e+02,   7.40000000e+01, ...,
          3.36000000e+01,   4.04000000e-01,   2.30000000e+01],
       [  4.00000000e+00,   7.60000000e+01,   6.20000000e+01, ...,
          3.40000000e+01,   3.91000000e-01,   2.50000000e+01],
       ..., 
       [  1.00000000e+00,   9.50000000e+01,   6.00000000e+01, ...,
          2.39000000e+01,   2.60000000e-01,   2.20000000e+01],
       [  1.00000000e+00,   1.06000000e+02,   7.60000000e+01, ...,
          3.75000000e+01,   1.97000000e-01,   2.60000000e+01],
       [  1.00000000e+01,   1.22000000e+02,   7.80000000e+01, ...,
          2.76000000e+01,   5.12000000e-01,   4.50000000e+01]])

In [17]:
x_test.shape

(231, 8)

In [18]:
x.shape

(768, 8)

In [19]:
y_train

array([1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0,
       0, 0,

In [20]:
y_train.shape

(537,)

In [21]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0])

In [22]:
y_test.shape

(231,)

In [23]:
y.shape

(768,)

In [24]:
import keras 
from keras.models import Sequential
from keras.layers import Dense
import numpy as np

Using TensorFlow backend.


# adding layers

In [25]:
model =Sequential()

In [26]:
model.add(Dense(12,input_dim=8,activation='relu')) #input layer

In [27]:
model.add(Dense(15,activation='relu'))             #hiddenlayer1

In [28]:
model.add(Dense(8,activation='relu'))              #hiddenlayer2

In [29]:
model.add(Dense(10,activation='relu'))             #hiddenlayer3

In [30]:
model.add(Dense(1,activation='sigmoid'))           #output layer

# compile

In [31]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [32]:
model.fit(x,y,epochs=1000,batch_size=10)

Epoch 1/1000
768/768 [==============================] - 1s 728us/step - loss: 0.9486 - acc: 0.5391
Epoch 2/1000
768/768 [==============================] - 0s 528us/step - loss: 0.7155 - acc: 0.6159
Epoch 3/1000
768/768 [==============================] - 0s 529us/step - loss: 0.7001 - acc: 0.6445
Epoch 4/1000
768/768 [==============================] - 0s 535us/step - loss: 0.7070 - acc: 0.6367
Epoch 5/1000
768/768 [==============================] - 0s 522us/step - loss: 0.6858 - acc: 0.6510
Epoch 6/1000
768/768 [==============================] - 0s 616us/step - loss: 0.6437 - acc: 0.6771
Epoch 7/1000
768/768 [==============================] - 0s 532us/step - loss: 0.6461 - acc: 0.6576
Epoch 8/1000
768/768 [==============================] - 0s 524us/step - loss: 0.6456 - acc: 0.6654
Epoch 9/1000
768/768 [==============================] - 0s 624us/step - loss: 0.6427 - acc: 0.6693
Epoch 10/1000
768/768 [==============================] - 0s 534us/step - loss: 0.6207 - acc: 0.6667
Epoch 11/

768/768 [==============================] - 0s 533us/step - loss: 0.4768 - acc: 0.7682
Epoch 84/1000
768/768 [==============================] - 0s 535us/step - loss: 0.4972 - acc: 0.7552
Epoch 85/1000
768/768 [==============================] - 0s 618us/step - loss: 0.4807 - acc: 0.7656
Epoch 86/1000
768/768 [==============================] - 0s 536us/step - loss: 0.4799 - acc: 0.7630
Epoch 87/1000
768/768 [==============================] - 0s 528us/step - loss: 0.4730 - acc: 0.7878
Epoch 88/1000
768/768 [==============================] - 0s 529us/step - loss: 0.4893 - acc: 0.7604
Epoch 89/1000
768/768 [==============================] - 0s 625us/step - loss: 0.4758 - acc: 0.7760
Epoch 90/1000
768/768 [==============================] - 0s 533us/step - loss: 0.4793 - acc: 0.7604
Epoch 91/1000
768/768 [==============================] - 0s 623us/step - loss: 0.4851 - acc: 0.7617
Epoch 92/1000
768/768 [==============================] - 0s 530us/step - loss: 0.4871 - acc: 0.7565
Epoch 93/1000


768/768 [==============================] - 0s 542us/step - loss: 0.4512 - acc: 0.7812
Epoch 164/1000
768/768 [==============================] - 0s 628us/step - loss: 0.4343 - acc: 0.8008
Epoch 165/1000
768/768 [==============================] - 0s 534us/step - loss: 0.4276 - acc: 0.8073
Epoch 166/1000
768/768 [==============================] - 0s 534us/step - loss: 0.4361 - acc: 0.7812
Epoch 167/1000
768/768 [==============================] - 0s 615us/step - loss: 0.4453 - acc: 0.7917
Epoch 168/1000
768/768 [==============================] - 0s 525us/step - loss: 0.4235 - acc: 0.8099
Epoch 169/1000
768/768 [==============================] - 0s 527us/step - loss: 0.4341 - acc: 0.8021
Epoch 170/1000
768/768 [==============================] - 0s 526us/step - loss: 0.4558 - acc: 0.7786 0s - loss: 0.4612 - acc: 0.76
Epoch 171/1000
768/768 [==============================] - 0s 534us/step - loss: 0.4271 - acc: 0.7917
Epoch 172/1000
768/768 [==============================] - 0s 616us/step - lo

768/768 [==============================] - 0s 616us/step - loss: 0.4317 - acc: 0.8021
Epoch 243/1000
768/768 [==============================] - 0s 536us/step - loss: 0.4009 - acc: 0.8203
Epoch 244/1000
768/768 [==============================] - 0s 534us/step - loss: 0.4148 - acc: 0.8021
Epoch 245/1000
768/768 [==============================] - 0s 618us/step - loss: 0.3968 - acc: 0.8190
Epoch 246/1000
768/768 [==============================] - 0s 537us/step - loss: 0.3919 - acc: 0.8164
Epoch 247/1000
768/768 [==============================] - 0s 536us/step - loss: 0.4005 - acc: 0.8177
Epoch 248/1000
768/768 [==============================] - 0s 534us/step - loss: 0.3902 - acc: 0.8203
Epoch 249/1000
768/768 [==============================] - 0s 527us/step - loss: 0.3921 - acc: 0.8294
Epoch 250/1000
768/768 [==============================] - 0s 538us/step - loss: 0.4231 - acc: 0.7969
Epoch 251/1000
768/768 [==============================] - 0s 628us/step - loss: 0.4012 - acc: 0.8073
Epoch

768/768 [==============================] - 0s 541us/step - loss: 0.3885 - acc: 0.8203
Epoch 323/1000
768/768 [==============================] - 0s 626us/step - loss: 0.3939 - acc: 0.8229
Epoch 324/1000
768/768 [==============================] - 0s 534us/step - loss: 0.3828 - acc: 0.8333
Epoch 325/1000
768/768 [==============================] - 0s 537us/step - loss: 0.3846 - acc: 0.8333
Epoch 326/1000
768/768 [==============================] - 0s 624us/step - loss: 0.4046 - acc: 0.8073
Epoch 327/1000
768/768 [==============================] - 0s 539us/step - loss: 0.3802 - acc: 0.8294
Epoch 328/1000
768/768 [==============================] - 0s 527us/step - loss: 0.3915 - acc: 0.8177
Epoch 329/1000
768/768 [==============================] - 0s 621us/step - loss: 0.3801 - acc: 0.8229
Epoch 330/1000
768/768 [==============================] - 0s 529us/step - loss: 0.3845 - acc: 0.8255
Epoch 331/1000
768/768 [==============================] - 0s 534us/step - loss: 0.3751 - acc: 0.8268 0s - 

768/768 [==============================] - 0s 534us/step - loss: 0.3730 - acc: 0.8255
Epoch 403/1000
768/768 [==============================] - 0s 630us/step - loss: 0.3663 - acc: 0.8216
Epoch 404/1000
768/768 [==============================] - 0s 541us/step - loss: 0.3967 - acc: 0.8138
Epoch 405/1000
768/768 [==============================] - 0s 630us/step - loss: 0.3765 - acc: 0.8359
Epoch 406/1000
768/768 [==============================] - 0s 534us/step - loss: 0.3993 - acc: 0.8125
Epoch 407/1000
768/768 [==============================] - 0s 629us/step - loss: 0.3920 - acc: 0.8255
Epoch 408/1000
768/768 [==============================] - 0s 541us/step - loss: 0.3690 - acc: 0.8255
Epoch 409/1000
768/768 [==============================] - 0s 635us/step - loss: 0.3695 - acc: 0.8281
Epoch 410/1000
768/768 [==============================] - 0s 536us/step - loss: 0.3640 - acc: 0.8294
Epoch 411/1000
768/768 [==============================] - 0s 629us/step - loss: 0.3726 - acc: 0.8372
Epoch

768/768 [==============================] - 0s 628us/step - loss: 0.3567 - acc: 0.8268
Epoch 483/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3537 - acc: 0.8398
Epoch 484/1000
768/768 [==============================] - 0s 627us/step - loss: 0.3428 - acc: 0.8451
Epoch 485/1000
768/768 [==============================] - 0s 542us/step - loss: 0.3500 - acc: 0.8398
Epoch 486/1000
768/768 [==============================] - 0s 532us/step - loss: 0.3606 - acc: 0.8398
Epoch 487/1000
768/768 [==============================] - 0s 618us/step - loss: 0.3642 - acc: 0.8294
Epoch 488/1000
768/768 [==============================] - 0s 540us/step - loss: 0.3513 - acc: 0.8490
Epoch 489/1000
768/768 [==============================] - 0s 625us/step - loss: 0.3567 - acc: 0.8398
Epoch 490/1000
768/768 [==============================] - 0s 539us/step - loss: 0.3520 - acc: 0.8424
Epoch 491/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3560 - acc: 0.8424
Epoch

768/768 [==============================] - 0s 640us/step - loss: 0.3523 - acc: 0.8359
Epoch 563/1000
768/768 [==============================] - 0s 632us/step - loss: 0.3615 - acc: 0.8372
Epoch 564/1000
768/768 [==============================] - 0s 527us/step - loss: 0.3351 - acc: 0.8411
Epoch 565/1000
768/768 [==============================] - 0s 531us/step - loss: 0.3936 - acc: 0.8216
Epoch 566/1000
768/768 [==============================] - 0s 531us/step - loss: 0.3449 - acc: 0.8477
Epoch 567/1000
768/768 [==============================] - 0s 625us/step - loss: 0.3447 - acc: 0.8411
Epoch 568/1000
768/768 [==============================] - 0s 532us/step - loss: 0.3566 - acc: 0.8385
Epoch 569/1000
768/768 [==============================] - 0s 536us/step - loss: 0.3559 - acc: 0.8372
Epoch 570/1000
768/768 [==============================] - 0s 621us/step - loss: 0.3523 - acc: 0.8385
Epoch 571/1000
768/768 [==============================] - 0s 529us/step - loss: 0.3681 - acc: 0.8437
Epoch

768/768 [==============================] - 0s 626us/step - loss: 0.3489 - acc: 0.8581 1s - loss: 0.3397 - acc: 0.
Epoch 643/1000
768/768 [==============================] - 0s 541us/step - loss: 0.3684 - acc: 0.8333
Epoch 644/1000
768/768 [==============================] - 0s 632us/step - loss: 0.3530 - acc: 0.8437
Epoch 645/1000
768/768 [==============================] - 0s 537us/step - loss: 0.3493 - acc: 0.8529
Epoch 646/1000
768/768 [==============================] - 0s 628us/step - loss: 0.3402 - acc: 0.8464
Epoch 647/1000
768/768 [==============================] - 0s 536us/step - loss: 0.3338 - acc: 0.8542
Epoch 648/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3568 - acc: 0.8385 0s - loss: 0.3027 - acc: 0.8
Epoch 649/1000
768/768 [==============================] - 0s 626us/step - loss: 0.3573 - acc: 0.8372
Epoch 650/1000
768/768 [==============================] - 0s 536us/step - loss: 0.3474 - acc: 0.8477
Epoch 651/1000
768/768 [=========================

768/768 [==============================] - 0s 543us/step - loss: 0.3341 - acc: 0.8516
Epoch 723/1000
768/768 [==============================] - 0s 626us/step - loss: 0.3511 - acc: 0.8372
Epoch 724/1000
768/768 [==============================] - 0s 540us/step - loss: 0.3431 - acc: 0.8424
Epoch 725/1000
768/768 [==============================] - 0s 616us/step - loss: 0.3510 - acc: 0.8372
Epoch 726/1000
768/768 [==============================] - 0s 531us/step - loss: 0.3507 - acc: 0.8346
Epoch 727/1000
768/768 [==============================] - 0s 532us/step - loss: 0.3282 - acc: 0.8555
Epoch 728/1000
768/768 [==============================] - 0s 627us/step - loss: 0.3204 - acc: 0.8529
Epoch 729/1000
768/768 [==============================] - 0s 538us/step - loss: 0.3330 - acc: 0.8542
Epoch 730/1000
768/768 [==============================] - 0s 631us/step - loss: 0.3372 - acc: 0.8411
Epoch 731/1000
768/768 [==============================] - 0s 543us/step - loss: 0.3526 - acc: 0.8464
Epoch

768/768 [==============================] - 0s 536us/step - loss: 0.3259 - acc: 0.8477
Epoch 801/1000
768/768 [==============================] - 0s 622us/step - loss: 0.3163 - acc: 0.8594
Epoch 802/1000
768/768 [==============================] - 0s 541us/step - loss: 0.3220 - acc: 0.8672
Epoch 803/1000
768/768 [==============================] - 0s 630us/step - loss: 0.3240 - acc: 0.8503
Epoch 804/1000
768/768 [==============================] - 0s 548us/step - loss: 0.3400 - acc: 0.8451
Epoch 805/1000
768/768 [==============================] - 0s 622us/step - loss: 0.3298 - acc: 0.8503
Epoch 806/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3402 - acc: 0.8424
Epoch 807/1000
768/768 [==============================] - 0s 625us/step - loss: 0.3276 - acc: 0.8542
Epoch 808/1000
768/768 [==============================] - 0s 537us/step - loss: 0.3402 - acc: 0.8411 0s - loss: 0.3521 - acc: 0.83
Epoch 809/1000
768/768 [==============================] - 0s 539us/step - lo

768/768 [==============================] - 0s 536us/step - loss: 0.3354 - acc: 0.8542
Epoch 881/1000
768/768 [==============================] - 0s 632us/step - loss: 0.3195 - acc: 0.8594
Epoch 882/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3310 - acc: 0.8568
Epoch 883/1000
768/768 [==============================] - 0s 534us/step - loss: 0.3280 - acc: 0.8490
Epoch 884/1000
768/768 [==============================] - 0s 623us/step - loss: 0.3254 - acc: 0.8542
Epoch 885/1000
768/768 [==============================] - 0s 537us/step - loss: 0.3173 - acc: 0.8555
Epoch 886/1000
768/768 [==============================] - 0s 624us/step - loss: 0.3305 - acc: 0.8620
Epoch 887/1000
768/768 [==============================] - 0s 543us/step - loss: 0.3219 - acc: 0.8659
Epoch 888/1000
768/768 [==============================] - 0s 626us/step - loss: 0.3212 - acc: 0.8477
Epoch 889/1000
768/768 [==============================] - 0s 535us/step - loss: 0.3282 - acc: 0.8568
Epoch

768/768 [==============================] - 0s 528us/step - loss: 0.3270 - acc: 0.8542
Epoch 961/1000
768/768 [==============================] - 0s 620us/step - loss: 0.4067 - acc: 0.8255
Epoch 962/1000
768/768 [==============================] - 0s 528us/step - loss: 0.3593 - acc: 0.8411
Epoch 963/1000
768/768 [==============================] - 0s 527us/step - loss: 0.3279 - acc: 0.8464
Epoch 964/1000
768/768 [==============================] - 0s 527us/step - loss: 0.3294 - acc: 0.8477
Epoch 965/1000
768/768 [==============================] - 0s 524us/step - loss: 0.3299 - acc: 0.8594
Epoch 966/1000
768/768 [==============================] - 0s 622us/step - loss: 0.3230 - acc: 0.8464
Epoch 967/1000
768/768 [==============================] - 0s 529us/step - loss: 0.3118 - acc: 0.8542
Epoch 968/1000
768/768 [==============================] - 0s 533us/step - loss: 0.3313 - acc: 0.8529
Epoch 969/1000
768/768 [==============================] - 0s 620us/step - loss: 0.3246 - acc: 0.8607
Epoch

In [33]:
model.save("diabetes.h5")

In [34]:
get_ipython().system(u'tar -zcvf diabetes.tgz diabetes.h5')

diabetes.h5


In [35]:
y_pred=model.predict(x_test)

In [36]:
y_pred

array([[  9.96754467e-01],
       [  1.88856367e-02],
       [  1.78492407e-03],
       [  7.67784655e-01],
       [  3.67575958e-02],
       [  1.97868515e-02],
       [  9.01337564e-01],
       [  9.81737912e-01],
       [  8.80212113e-02],
       [  4.35761213e-01],
       [  7.52546310e-01],
       [  9.86679971e-01],
       [  4.86293662e-04],
       [  5.67688327e-03],
       [  6.53495640e-02],
       [  2.22011656e-01],
       [  8.87746990e-01],
       [  1.09362295e-02],
       [  7.90636539e-02],
       [  1.87691629e-01],
       [  5.64935744e-01],
       [  9.31239605e-01],
       [  3.12871225e-02],
       [  1.19208083e-01],
       [  1.04900624e-03],
       [  3.14964324e-01],
       [  4.18385975e-02],
       [  1.24666601e-01],
       [  1.36421144e-01],
       [  7.94837028e-02],
       [  5.68134785e-01],
       [  1.45412594e-01],
       [  4.80900810e-04],
       [  5.78806520e-01],
       [  5.19240275e-02],
       [  9.12044704e-01],
       [  9.55018759e-01],
 

In [37]:
y_test

array([1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0])

In [38]:
y_pred1 = model.predict(np.array([[5,116,74,0,0,25.6,0.201,30]]))

In [39]:
y_pred1

array([[ 0.07549611]], dtype=float32)

In [40]:
y_pred2 =model.predict(np.array([[15,136,70,32,110,37.1,0.153,43]]))

In [41]:
y_pred2

array([[ 0.9291274]], dtype=float32)

In [42]:
y_pred3 = model.predict(np.array([[0,125,96,0,0,22.5,0.262,21]]))

In [43]:
y_pred3

array([[ 0.03878843]], dtype=float32)

In [44]:
y_pred4 = model.predict(np.array([[8,179,72,42,130,32.7,0.719,36]]))

In [45]:
y_pred4

array([[ 0.88774699]], dtype=float32)

In [46]:
y_pred5 = model.predict(np.array([[11,103,68,40,0,46.2,0.126,42]]))

In [47]:
y_pred5

array([[ 0.45181456]], dtype=float32)

In [48]:
y_pred6 = model.predict(np.array([[6,148,72,35,0,33.6,0.627,50]]))

In [49]:
y_pred6

array([[ 0.84457356]], dtype=float32)

In [50]:
y_pred7 = model.predict(np.array([[1,93,70,31,0,30.4,0.315,23]]))

In [51]:
y_pred7

array([[ 0.02060651]], dtype=float32)

In [52]:
!pip install watson_machine_learning_client

tensorflow 1.3.0 requires tensorflow-tensorboard<0.2.0,>=0.1.0, which is not installed.


In [55]:
from watson_machine_learning_client import WatsonMachineLearningAPIClient

In [56]:
wml_credentials={
     "url":  "https://eu-gb.ml.cloud.ibm.com",
  "access_key":"t1899jznDXJ6r_Z1-ikVQJ8iFx4rKEAkO6n8y9MYQ3KA",
  "username":  "3dd47c6e-2de6-4dcf-a3a1-608d97456712",
  "password":  "d44fc874-897e-4aaa-8c6c-a9397eb61cca",
  "instance_id":"9a7a83ec-3888-42ad-bf6a-062e56368d02",
}

In [57]:
client = WatsonMachineLearningAPIClient(wml_credentials)

In [58]:
metadata ={
     client.repository.ModelMetaNames.NAME: "keras model",
    client.repository.ModelMetaNames.FRAMEWORK_NAME: "tensorflow",
    client.repository.ModelMetaNames.FRAMEWORK_LIBRARIES:[{'name':'keras','version':'2.1.3'}],
    client.repository.ModelMetaNames.FRAMEWORK_VERSION: "1.5"
}    



In [59]:
model_details = client.repository.store_model( model="diabetes.tgz", meta_props=metadata )

In [60]:
model_id = model_details["metadata"]["guid"]

In [61]:
model_deployment_details = client.deployments.create( artifact_uid=model_id, name="deployment" )




#######################################################################################

Synchronous deployment creation for uid: '722ced57-945b-41be-97c6-eabb7c673f84' started

#######################################################################################


INITIALIZING
DEPLOY_IN_PROGRESS
DEPLOY_SUCCESS


------------------------------------------------------------------------------------------------
Successfully finished deployment creation, deployment_uid='f4e081de-a75e-4ebc-9d9d-a0c9bc2e724f'
------------------------------------------------------------------------------------------------




In [62]:
scoring_endpoint = client.deployments.get_scoring_url(model_deployment_details)

In [63]:
scoring_endpoint

'https://eu-gb.ml.cloud.ibm.com/v3/wml_instances/9a7a83ec-3888-42ad-bf6a-062e56368d02/deployments/f4e081de-a75e-4ebc-9d9d-a0c9bc2e724f/online'

In [64]:
scoring_payload = {"fields":["Prediction"],"values":[[8,183,64,0,0,23.3,0.672,32]]}

In [65]:
predictions = client.deployments.score(scoring_endpoint,scoring_payload)

In [66]:
predictions

{'fields': ['prediction', 'prediction_classes', 'probability'],
 'values': [[[0.8802562355995178], [1], [0.8802562355995178]]]}